name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/Backend/Backend.csproj

    - name: Build
      run: dotnet build src/Backend/Backend.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test tests/Backend.Tests/Backend.Tests.csproj --configuration Release --no-build --verbosity normal